// Copyright (C) 2025 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.gradle.artifacts

import kotlin.io.path.bufferedWriter
import kotlin.io.path.deleteIfExists
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Aggregates Metro graph metadata JSON files into a single consolidated report on a per-compilation
 * basis.
 *
 * This task collects all graph metadata JSON files generated by the Metro compiler plugin in a
 * given compilation and combines them into a single JSON file containing metadata about all
 * dependency graphs in the project. The output includes the project path, graph count, and an array
 * of all individual graph metadata objects.
 *
 * The generated file is useful for:
 * - CI validation of dependency graph structure
 * - Automated analysis and reporting
 * - Tooling that needs a complete view of all Metro graphs in a project
 */
@CacheableTask
public abstract class GenerateGraphMetadataTask : DefaultTask() {

  /** The Gradle project path this task is generating metadata for. */
  @get:Input public abstract val projectPath: Property<String>

  /** The kotlinc compilation name. */
  @get:Input @get:Optional public abstract val compilationName: Property<String>

  /** The graph metadata JSON files. */
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  public abstract val graphJsonFiles: ConfigurableFileCollection

  /** The output file where the consolidated metadata will be written. */
  @get:OutputFile public abstract val outputFile: RegularFileProperty

  private val json = Json {
    prettyPrint = true
    @OptIn(ExperimentalSerializationApi::class)
    prettyPrintIndent = "  "
    encodeDefaults = true
  }

  init {
    group = "metro"
  }

  // TODO sort outputs further?
  @TaskAction
  public fun generate() {
    val output = outputFile.get().asFile.toPath()
    output.deleteIfExists()

    // Track seen graph names to deduplicate (KMP projects may have same graph in multiple targets)
    val seenGraphs = mutableSetOf<String>()

    val graphJsonElements =
      graphJsonFiles
        .asSequence()
        .onEach { file -> logger.lifecycle("Merging metro graph metadata file $file") }
        .sortedBy { it.absolutePath }
        .mapNotNull { file ->
          runCatching { json.parseToJsonElement(file.readText()) }
            .getOrElse { throwable ->
              logger.error(
                "Failed to parse Metro graph metadata file ${file.absolutePath}",
                throwable,
              )
              null
            }
        }
        .filter { element ->
          // Deduplicate by graph name - in KMP projects, the same graph may be compiled
          // by multiple targets (e.g., android and jvm both compiling shared code)
          val graphName =
            (element as? JsonObject)?.get("graph")?.let { (it as? JsonPrimitive)?.content }
          if (graphName != null && !seenGraphs.add(graphName)) {
            logger.lifecycle("Skipping duplicate graph: $graphName")
            false
          } else {
            true
          }
        }
        .toList()

    val result = buildJsonObject {
      put("projectPath", JsonPrimitive(projectPath.get()))
      put("graphCount", JsonPrimitive(graphJsonElements.size))
      put("graphs", JsonArray(graphJsonElements))
    }

    output.bufferedWriter().use { writer ->
      writer.write(json.encodeToString(JsonObject.serializer(), result))
    }
    logger.lifecycle("Generated metro graph metadata file to file://$output")
  }

  internal companion object {
    const val NAME = "generateMetroGraphMetadata"
  }
}
